<template>

    <div class="flex-1 px-4 mx-4 max-w-prose mx-auto">

        <h2 class="text-3xl m-8">Setup TOTP multi-factor authentication</h2>

        <div v-if="error" class="flex p-4 mb-4 text-sm text-red-800 border border-red-300 rounded-lg bg-red-50 dark:bg-gray-800 dark:text-red-400 dark:border-red-800" role="alert">
            <svg aria-hidden="true" class="flex-shrink-0 inline w-5 h-5 mr-3" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd"></path></svg>
            <span class="sr-only">Info</span>
            <p>{{ error }}</p>
        </div>

        <div v-if="success" class="flex p-4 mb-4 text-sm text-green-800 rounded-lg bg-green-50 dark:bg-gray-800 dark:text-green-400" role="alert">
            <svg aria-hidden="true" class="flex-shrink-0 inline w-5 h-5 mr-3" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd"></path></svg>
            <span class="sr-only">Info</span>
            <p>Your account is now protected by multi-factor authentication. Remember to save your backup codes.</p>
        </div>

        <button v-if="!data.qrcode && !mfaEnabled" @click="startEnablingTotp" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Enable</button> 

        <button v-else-if="mfaEnabled" @click="modal.toggle()" data-modal-target="show-backup-codes-modal" data-modal-toggle="show-backup-codes-modal" class="mt-5 text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Show backup codes</button>

        <div v-else-if="data.qrcode && !mfaEnabled" class="mb-5">

            <p>Install Authenticator application (such as <span class="font-bold">Google Authenticator</span>, <span class="font-bold">Authy</span> or <span class="font-bold">Aegis</span>) on your mobile device then scan QR code below.</p>
        
            <img :src="data.qrcode" class="mx-auto" alt="QR code">

            <p>If you cannot scan QR code, you can enter secret code manually: <span class="font-bold">{{ data.base32 }}</span></p>

            <p class="mt-2">Next, enter the 6-digit code generated by the authenticator app.</p>

            <form @submit.prevent="enableTotp" class="mt-5">

                <div class="mb-4">
                    <label for="token" class="block mb-1 text-sm font-medium text-gray-900 dark:text-white">Code</label>
                    <input 
                        v-model="token" 
                        type="text" 
                        name="token"
                        maxlength="6"
                        class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                    >
                </div>

                <button type="submit" class="float-right my-2 text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Enable</button>

            </form>

        </div>

        <div id="show-backup-codes-modal" tabindex="-1" aria-hidden="true" class="block fixed top-0 left-0 right-0 z-50 hidden w-full p-4 overflow-x-hidden overflow-y-auto md:inset-0 h-[calc(100%-1rem)] max-h-full">
            <div class="relative w-full max-w-md max-h-full lg:h-auto mx-auto">
                <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">

                    <button type="button" class="absolute top-3 right-2.5 text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center dark:hover:bg-gray-800 dark:hover:text-white" data-modal-hide="show-backup-codes-modal">
                        <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
                        <span class="sr-only">Close modal</span>
                    </button>

                    <div class="px-6 py-6 lg:px-8">

                        <h3 class="mb-4 text-xl font-medium text-gray-900 dark:text-white">Your backup codes</h3>
                        
                        <div v-if="error" class="flex p-4 mb-4 text-sm text-red-800 border border-red-300 rounded-lg bg-red-50 dark:bg-gray-800 dark:text-red-400 dark:border-red-800" role="alert">
                            <svg aria-hidden="true" class="flex-shrink-0 inline w-5 h-5 mr-3" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd"></path></svg>
                            <span class="sr-only">Info</span>
                            <p>{{ error }}</p>
                        </div>

                        <p>Just save this codes in a safe place. In case you lose access to the authenticator app, you will use them to log in. Each of the codes below is a one-time use.</p>

                        <p v-if="!backupCodes.length" class="text-red-500 font-bold my-2">You've run out of backup codes!</p>
                        
                        <div v-else class="grid gap-3 mb-5 md:grid-cols-2 mt-4">
                            <p v-for="(code, i) in backupCodes" :key="i">{{ code }}</p>
                        </div>

                        <button @click="regenerateBackupCodes" class="mt-2 text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Regenerate backup codes</button>

                    </div>

                </div>
            </div>
        </div>

    </div>

</template>


<script setup>

import { ref, onMounted } from "vue";
import { Modal } from "flowbite";

const error = ref("");
const data = ref({});

const mfaEnabled = ref(0);
const backupCodes = ref([]);

const modal = ref({});

onMounted(async () => {

    modal.value = new Modal(document.getElementById("show-backup-codes-modal"));

    try {

        const res = await fetch("/api/user/me");

        if(!res.ok) throw new Error("Failed to connect with API server");
        const body = await res.json();

        if(!body.success) throw new Error(body.error);

        if(body.data.backupCodes) backupCodes.value = body.data.backupCodes;

        return mfaEnabled.value = body.data.mfaEnabled;

    } catch(err) {
        console.error(err);
        error.value = err.message;
    }

});

const startEnablingTotp = async () => {

    error.value = "";

    try {

        const res = await fetch("/api/user/settings/totp/start");

        if(!res.ok) throw new Error("Failed to connect with API server");
        const body = await res.json();

        if(!body.success) throw new Error(body.error);

        return data.value = body.data;

    } catch(err) {
        console.error(err);
        error.value = err.message;
    }

}

const token = ref("");
const success = ref(0);

const enableTotp = async () => {

    error.value = "";

    try {

        const { secret, base32 } = data.value; 

        const res = await fetch("/api/user/settings/totp/enable", {
            method: "POST",
            headers: {
                "Content-Type": "application/json"
            },
            body: JSON.stringify({ 
                secret,
                token: token.value
            })
        });

        if(!res.ok) throw new Error("Failed to connect with API server");
        const body = await res.json();

        if(!body.success) throw new Error(body.error);

        data.value = {};
        success.value = true;
        mfaEnabled.value = true;

    } catch(err) {
        console.error(err);
        error.value = err.message;
    }

}

const regenerateBackupCodes = async () => {

    error.value = "";

    try {

        const res = await fetch("/api/user/settings/totp/regenerate-backup-codes");

        if(!res.ok) throw new Error("Failed to connect with API server");
        const body = await res.json();

        if(!body.success) throw new Error(body.error);

        backupCodes.value = body.data.codes;

    } catch(err) {
        console.error(err);
        error.value = err.message;
    }

}

</script>